title = "Fimbo Vibes"
baseURL = "https://amazing-fairy-5e81f2.netlify.app/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "timetable"
    name = "Timetable"
    url = "/timetable"
    weight = 20
  [[menu.main]]
    identifier = "instructors"
    name = "Instructors"
    url = "/instructors"
    weight = 30
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news"
    weight = 40

