title = "Fimbo Vibes"

[menu]
  [[menu.main]]
    identifier = "timetable"
    name = "Timetable"
    url = "/timetable"
    weight = 10
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news"
    weight = 20

