title = "Fimbo Vibes"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageref = "/"
    weight = 10
  [[menu.main]]
    identifier = "timetable"
    name = "Timetable"
    pageref = "/timetable"
    weight = 20
  [[menu.main]]
    identifier = "news"
    name = "News"
    pageref = "/news"
    weight = 30

